### ISSUE TITLE
Coverage is totally wrong when using --circleci-parallelize

### ISSUE THREAD

**Issue by cscetbon** [ryanwilsonperkin/pytest-circleci-parallelized#11]
When I use --circleci-parallelize I get a coverage of 68% while I get a coverage of 94% without...
<img width="426" alt="Screen Shot 2022-06-29 at 3 34 28 PM" src="https://user-images.githubusercontent.com/2619840/176521126-6f52f133-cd9b-4f1e-8b6c-3c7986f16d2f.png">

<img width="394" alt="Screen Shot 2022-06-29 at 3 34 58 PM" src="https://user-images.githubusercontent.com/2619840/176521108-a5fb771d-8dd4-43fa-bf61-592e92a7cb35.png">

**Comment by RJPercival** [comment]
You need to use [coverage.py's **combine** command](https://coverage.readthedocs.io/en/stable/cmd.html#cmd-combine) to merge each worker's coverage report to get the overall coverage. Each worker will tell you only what coverage its subset of the tests provided.

**Comment by RJPercival** [comment]
Duplicate of #7.
