### ISSUE TITLE
Split by name option for circleci

### ISSUE THREAD

**Issue by aristoHero** [ryanwilsonperkin/pytest-circleci-parallelized#14]
Hello,
I would like to split tests based on name rather than timing. Can we also get support for that?

**Comment by ryanwilsonperkin** [comment]
I believe you can do this with the pytest-split package and would probably be a better fit since that functionality isn't particular to CircleCi. This package aims to provide a narrow scope for splitting based on the timing behaviour

**Comment by aristoHero** [comment]
ok. thank you
